/* ============================================================
   treatments.js — 시술소개 홈 데이터
   · CONCERNS : 고민 키워드(칩). 시술이 1개라도 달린 고민만 노출돼요.
   · TREATMENTS : 각 시술은 c[]에 '대표 고민' 1개만 달아, 고민별 추천이
     서로 겹치지 않게 했어요. 더 노출하고 싶으면 c 배열에 id를 추가하세요.
  · href 규칙: "details/시술소개 - {시술명}.html"
   ============================================================ */

const CONCERNS = [
  { id:"sagging", label:"처진 턱선·볼" },
  { id:"elasticity", label:"피부 탄력" },
  { id:"fine_lines", label:"잔주름·피부결" },
  { id:"regen", label:"피부 재생·생기" },
  { id:"skin_quality", label:"피부결·밀도" },
  { id:"hydration", label:"건조·수분" },
  { id:"double_chin", label:"이중턱·심부볼" },
  { id:"pores", label:"넓은 모공" },
  { id:"acne_scar", label:"여드름 흉터" },
  { id:"acne", label:"여드름·트러블" },
  { id:"redness", label:"홍조·붉은기" },
  { id:"pigment", label:"기미·잡티·색소" },
  { id:"dull_tone", label:"칙칙한 피부톤" },
  { id:"mole", label:"점·검버섯 제거" },
  { id:"keratin", label:"각질·블랙헤드" },
  { id:"sensitive", label:"예민·진정" },
  { id:"aftercare", label:"시술 후 진정케어" },
  { id:"wrinkle_forehead", label:"이마 주름" },
  { id:"wrinkle_glabella", label:"미간 주름" },
  { id:"wrinkle_eye", label:"눈가 주름" },
  { id:"nasolabial", label:"팔자·마리오네트" },
  { id:"neck", label:"목 라인·목주름" },
  { id:"volume_cheek", label:"볼·광대 꺼짐" },
  { id:"volume_eye", label:"눈밑·다크서클" },
  { id:"volume_temple", label:"관자놀이·눈두덩이" },
  { id:"contour_chin", label:"무턱·턱끝·턱라인" },
  { id:"nose", label:"코 윤곽" },
  { id:"lips", label:"입술·입매" },
  { id:"eye_charm", label:"애교살" },
  { id:"mouth_corner", label:"처진 입꼬리" },
  { id:"square_jaw", label:"사각턱" },
  { id:"face_slim", label:"얼굴 갸름(침샘)" },
  { id:"gummy", label:"잇몸 미소" },
  { id:"mini_botox", label:"콧볼·콧등·자갈턱" },
  { id:"body_line", label:"어깨·종아리 라인" },
  { id:"body_skin", label:"복부·바디 탄력" },
  { id:"sweat", label:"다한증" },
  { id:"tmj", label:"이갈이·턱관절" },
  { id:"hands", label:"손등" },
  { id:"nail", label:"손발톱무좀" },
  { id:"head_shape", label:"두상" },
  { id:"scalp", label:"두피·모발" },
  { id:"filler_fix", label:"필러 정리·교정" },
];

const TREATMENTS = [
  /* ── 리프팅·탄력 ── */
  { n:"울쎄라", en:"Ulthera", cat:"리프팅·탄력", d:"피부 깊은 SMAS층에 초음파 열을 전달해 처진 피부를 끌어올리는 리프팅 시술이에요.", c:["sagging"], dt:"none", multi:false, area:"face", method:"energy", pain:1, onset:"gradual", href:"details/시술소개 - 울쎄라.html" },
  { n:"써마지", en:"Thermage FLX", cat:"리프팅·탄력", d:"고주파 열로 진피 콜라겐을 조여 피부를 탄탄하게 만드는 타이트닝 시술이에요.", c:["elasticity"], dt:"none", multi:false, area:"face", method:"energy", pain:1, onset:"gradual", href:"details/시술소개 - 써마지.html" },
  { n:"슈링크", en:"Shurink", cat:"리프팅·탄력", d:"초음파 열을 피부 속 여러 깊이에 전달해 탄력을 끌어올리는 HIFU 리프팅 시술이에요.", c:["sagging"], dt:"none", multi:false, area:"face", method:"energy", pain:1, onset:"gradual", href:"details/시술소개 - 슈링크.html" },
  { n:"인모드", en:"InMode", cat:"리프팅·탄력", d:"고주파와 진공 흡입으로 지방을 줄이고 탄력을 함께 잡는 복합 리프팅 시술이에요.", c:["double_chin"], dt:"none", multi:true, area:"face", method:"energy", pain:1, onset:"gradual", href:"details/시술소개 - 인모드.html" },
  { n:"올리지오", en:"Oligio", cat:"리프팅·탄력", d:"모노폴라 고주파 열로 진피 콜라겐을 자극해 피부를 탄탄하게 하는 타이트닝 시술이에요.", c:["elasticity"], dt:"none", multi:false, area:"face", method:"energy", pain:1, onset:"gradual", href:"details/시술소개 - 올리지오.html" },
  { n:"덴서티", en:"Density", cat:"리프팅·탄력", d:"단극성·양극성 고주파를 함께 써서 진피 콜라겐을 자극하는 타이트닝 시술이에요.", c:["elasticity"], dt:"none", multi:false, area:"face", method:"energy", pain:1, onset:"gradual", href:"details/시술소개 - 덴서티.html" },
  { n:"볼뉴머", en:"Volnewmer", cat:"리프팅·탄력", d:"모노폴라 고주파 열로 진피 콜라겐을 조여 피부를 탄탄하게 하는 타이트닝 시술이에요.", c:["elasticity"], dt:"none", multi:false, area:"face", method:"energy", pain:1, onset:"gradual", href:"details/시술소개 - 볼뉴머.html" },
  { n:"포텐자", en:"Potenza", cat:"리프팅·탄력", d:"미세 바늘로 진피에 고주파를 직접 전달해 탄력과 피부결을 함께 개선하는 시술이에요.", c:["pores"], dt:"some", multi:false, area:"face", method:"needle", pain:3, onset:"gradual", href:"details/시술소개 - 포텐자.html" },
  { n:"모피우스8", en:"Morpheus8", cat:"리프팅·탄력", d:"미세 바늘로 진피와 지방층까지 고주파를 전달해 리모델링하는 니들 RF 리프팅 시술이에요.", c:["acne_scar"], dt:"some", multi:false, area:"face", method:"needle", pain:3, onset:"gradual", href:"details/시술소개 - 모피우스8.html" },
  { n:"엠페이스", en:"Emface", cat:"리프팅·탄력", d:"고주파와 전기 자극을 동시에 줘서 피부와 얼굴 근육을 함께 끌어올리는 리프팅 시술이에요.", c:["sagging"], dt:"none", multi:false, area:"face", method:"energy", pain:1, onset:"gradual", href:"details/시술소개 - 엠페이스.html" },
  { n:"리프테라", en:"Liftera", cat:"리프팅·탄력", d:"약한 초음파 열을 촘촘히 전달해 부담 없이 탄력을 챙기는 입문형 HIFU 리프팅이에요.", c:["elasticity"], dt:"none", multi:true, area:"face", method:"energy", pain:1, onset:"gradual", href:"details/시술소개 - 리프테라.html" },
  { n:"쿨소닉", en:"CoolSoniq", cat:"리프팅·탄력", d:"냉각 기술을 더해 통증을 줄인 고출력 HIFU 리프팅이에요.", c:["sagging"], dt:"none", multi:false, area:"face", method:"energy", pain:1, onset:"gradual", href:"details/시술소개 - 쿨소닉.html" },
  { n:"더블로골드", en:"Doublo Gold", cat:"리프팅·탄력", d:"진피와 SMAS층에 초음파 열을 전달해 처진 피부를 끌어올리는 HIFU 리프팅이에요.", c:["sagging"], dt:"none", multi:false, area:"face", method:"energy", pain:1, onset:"gradual", href:"details/시술소개 - 더블로골드.html" },
  { n:"브이로", en:"V-RO", cat:"리프팅·탄력", d:"초음파(HIFU)에 고주파(RF)를 더한 더블로 시리즈의 최신 리프팅 장비예요.", c:["sagging"], dt:"none", multi:false, area:"face", method:"energy", pain:1, onset:"gradual", href:"details/시술소개 - 브이로.html" },
  { n:"리니어지", en:"LinearZ", cat:"리프팅·탄력", d:"점·선 두 방식으로 다양한 깊이에 초음파 열을 전달하는 HIFU 리프팅이에요.", c:["sagging"], dt:"none", multi:false, area:"face", method:"energy", pain:1, onset:"gradual", href:"details/시술소개 - 리니어지.html" },
  { n:"소프웨이브", en:"Sofwave", cat:"리프팅·탄력", d:"진피 1.5mm에 7개 초음파 빔을 보내 표면 손상 없이 잔주름·탄력을 잡는 리프팅이에요.", c:["fine_lines"], dt:"none", multi:false, area:"face", method:"energy", pain:1, onset:"gradual", href:"details/시술소개 - 소프웨이브.html" },
  { n:"울트라셀Q+", en:"ULTRAcel Q+", cat:"리프팅·탄력", d:"점·선 초음파 열을 SMAS층에 전달해 처진 피부를 끌어올리는 HIFU 리프팅이에요.", c:["sagging"], dt:"none", multi:false, area:"face", method:"energy", pain:1, onset:"gradual", href:"details/시술소개 - 울트라셀Q.html" },
  { n:"온다", en:"ONDA", cat:"리프팅·탄력", d:"극초단파(마이크로웨이브)로 지방을 줄이고 피부를 탄탄하게 조이는 리프팅 시술이에요.", c:["double_chin"], dt:"none", multi:true, area:"face", method:"energy", pain:1, onset:"gradual", href:"details/시술소개 - 온다.html" },
  { n:"윈백", en:"Winback", cat:"리프팅·탄력", d:"테카(TECAR) 고주파로 피부 안쪽에서 심부열을 만들어 탄력을 관리하는 리프팅 케어예요.", c:["elasticity"], dt:"none", multi:true, area:"face", method:"energy", pain:1, onset:"gradual", href:"details/시술소개 - 윈백.html" },
  { n:"앤디메드", en:"ENDYMED", cat:"리프팅·탄력", d:"여러 전극으로 입체적으로 고주파 열을 전달해 탄력과 피부결을 개선하는 리프팅이에요.", c:["elasticity"], dt:"none", multi:false, area:"face", method:"energy", pain:1, onset:"gradual", href:"details/시술소개 - 앤디메드.html" },
  { n:"세르프", en:"XERF", cat:"리프팅·탄력", d:"두 가지 주파수의 모노폴라 고주파로 얕은 층부터 깊은 층까지 끌어올리는 리프팅이에요.", c:["sagging"], dt:"none", multi:false, area:"face", method:"energy", pain:1, onset:"gradual", href:"details/시술소개 - 세르프.html" },
  { n:"쿨페이즈", en:"Coolfase", cat:"리프팅·탄력", d:"냉각 기술을 더한 모노폴라 고주파로 통증을 줄이며 탄력을 잡는 리프팅이에요.", c:["elasticity"], dt:"none", multi:false, area:"face", method:"energy", pain:1, onset:"gradual", href:"details/시술소개 - 쿨페이즈.html" },
  { n:"버츄RF", en:"Virtue RF", cat:"리프팅·탄력", d:"미세 바늘로 진피에 고주파를 직접 전달해 탄력과 피부결을 개선하는 니들 RF 시술이에요.", c:["acne_scar"], dt:"some", multi:false, area:"face", method:"needle", pain:3, onset:"gradual", href:"details/시술소개 - 버츄RF.html" },
  { n:"프로파운드", en:"Profound", cat:"리프팅·탄력", d:"니들로 진피·피하층에 고주파 열을 정밀하게 가해 강하게 끌어올리는 니들 RF 리프팅이에요.", c:["sagging"], dt:"some", multi:false, area:"face", method:"needle", pain:3, onset:"gradual", href:"details/시술소개 - 프로파운드.html" },
  { n:"튠", en:"Tune", cat:"리프팅·탄력", d:"진공으로 피부를 잡고 멀티 고주파를 전달해 탄력을 끌어올리는 RF 리프팅이에요. (니들 방식 아님)", c:["elasticity"], dt:"none", multi:false, area:"face", method:"energy", pain:1, onset:"gradual", href:"details/시술소개 - 튠.html" },
  { n:"BBL", en:"BroadBand Light", cat:"리프팅·탄력", d:"광대역광(빛)으로 색소·홍조를 다스리며 콜라겐을 자극하는 빛 기반 피부 관리예요.", c:["pigment"], dt:"none", multi:false, area:"face", method:"energy", pain:1, onset:"gradual", href:"details/시술소개 - BBL.html" },
  { n:"LDM", en:"", cat:"리프팅·탄력", d:"서로 다른 초음파를 빠르게 교차해 피부를 미세하게 마사지하며 재생·탄력을 돕는 저자극 관리예요.", c:["sensitive"], dt:"none", multi:false, area:"face", method:"energy", pain:1, onset:"gradual", href:"details/시술소개 - LDM.html" },
  { n:"티타늄", en:"", cat:"리프팅·탄력", d:"세 가지 파장의 다이오드 레이저로 진피에 열을 전달해 탄력·피부톤을 개선하는 빛 기반 시술이에요.", c:["fine_lines"], dt:"none", multi:false, area:"face", method:"energy", pain:1, onset:"gradual", href:"details/시술소개 - 티타늄.html" },
  { n:"텐써마", en:"10THERMA", cat:"리프팅·탄력", d:"고출력 모노폴라 고주파로 진피 콜라겐을 자극해 탄력을 끌어올리는 타이트닝 시술이에요.", c:["elasticity"], dt:"none", multi:false, area:"face", method:"energy", pain:1, onset:"gradual", href:"details/시술소개 - 텐써마.html" },
  { n:"텐쎄라", en:"10THERA", cat:"리프팅·탄력", d:"2라인 초음파로 진피와 SMAS층을 끌어올리는 HIFU 리프팅이에요.", c:["sagging"], dt:"none", multi:false, area:"face", method:"energy", pain:1, onset:"gradual", href:"details/시술소개 - 텐쎄라.html" },
  { n:"올타이트", en:"Alltite", cat:"리프팅·탄력", d:"유전가열(DLTD) 고주파로 진피부터 SMAS층까지 데워 끌어올리는 리프팅이에요.", c:["sagging"], dt:"none", multi:false, area:"face", method:"energy", pain:1, onset:"gradual", href:"details/시술소개 - 올타이트.html" },
  { n:"이브타이탄", en:"EVE Titan", cat:"리프팅·탄력", d:"고주파와 전기 근육 자극(EMS)으로 근육층까지 자극해 끌어올리는 리프팅이에요.", c:["sagging"], dt:"none", multi:false, area:"face", method:"energy", pain:1, onset:"gradual", href:"details/시술소개 - 이브타이탄.html" },
  { n:"울핏", en:"ULFIT", cat:"리프팅·탄력", d:"집속 초음파로 복부·허벅지 등 바디의 지방과 처짐을 함께 잡는 바디 HIFU 리프팅이에요.", c:["body_skin"], dt:"none", multi:false, area:"body", method:"energy", pain:1, onset:"gradual", href:"details/시술소개 - 울핏.html" },
  { n:"셀리뉴", en:"Cellinew", cat:"리프팅·탄력", d:"모노폴라 고주파로 진피를 데워 콜라겐을 리모델링하는 타이트닝 시술이에요.", c:["elasticity"], dt:"none", multi:false, area:"face", method:"energy", pain:1, onset:"gradual", href:"details/시술소개 - 셀리뉴.html" },
  /* ── 스킨부스터 ── */
  { n:"리쥬란힐러", en:"", cat:"스킨부스터", d:"연어 DNA 유래 PN 성분으로 피부 자체의 재생력을 끌어올리는 스킨부스터예요.", c:["regen"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 리쥬란힐러.html" },
  { n:"리쥬란HB", en:"", cat:"스킨부스터", d:"기존 리쥬란힐러에 마취 성분과 히알루론산을 더해 통증은 줄이고 물광은 더한 스킨부스터예요.", c:["hydration"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 리쥬란HB.html" },
  { n:"리쥬란아이", en:"", cat:"스킨부스터", d:"얇은 눈가 피부에 맞춰 설계된 PN 성분으로 눈가 잔주름과 다크서클을 가꾸는 스킨부스터예요.", c:["wrinkle_eye"], dt:"some", multi:true, area:"eye", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 리쥬란아이.html" },
  { n:"리쥬란에스", en:"", cat:"스킨부스터", d:"패인 흉터와 고르지 않은 피부결 개선에 초점을 둔 PN 성분 스킨부스터예요.", c:["acne_scar"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 리쥬란에스.html" },
  { n:"리쥬란시너지 스킨부스터", en:"", cat:"스킨부스터", d:"피부에 바르는 c-PDRN 성분 화장품으로 탄력·재생 관리를 돕는 부스터예요.", c:["aftercare"], dt:"none", multi:true, area:"face", method:"topical", pain:0, onset:"gradual", href:"details/시술소개 - 리쥬란시너지 스킨부스터.html" },
  { n:"리쥬란시너지 톤업부스터", en:"", cat:"스킨부스터", d:"바르는 c-PDRN 성분 화장품으로 칙칙한 피부 톤 관리를 돕는 부스터예요.", c:["dull_tone"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 리쥬란시너지 톤업부스터.html" },
  { n:"쥬베룩", en:"", cat:"스킨부스터", d:"PDLLA 성분으로 피부가 스스로 콜라겐을 만들도록 돕는 콜라겐 부스터예요.", c:["skin_quality"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 쥬베룩.html" },
  { n:"쥬베룩볼륨", en:"", cat:"스킨부스터", d:"입자가 큰 PDLLA로 꺼진 부위를 자연스러운 콜라겐으로 채워주는 콜라겐 부스터예요.", c:["volume_cheek"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 쥬베룩볼륨.html" },
  { n:"쥬베룩아이", en:"", cat:"스킨부스터", d:"가장 작은 입자의 PDLLA로 얇은 눈가에 맞춘 콜라겐 부스터예요.", c:["wrinkle_eye"], dt:"some", multi:true, area:"eye", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 쥬베룩아이.html" },
  { n:"스컬트라", en:"", cat:"스킨부스터", d:"PLLA 성분으로 피부 속 콜라겐 생성을 촉진하는 콜라겐 바이오스티뮬레이터예요.", c:["volume_cheek"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 스컬트라.html" },
  { n:"스킨바이브", en:"", cat:"스킨부스터", d:"피부 속에 히알루론산을 미세하게 주입해 수분과 피부결을 채우는 수분 스킨부스터예요.", c:["hydration"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 스킨바이브.html" },
  { n:"잘루프로클래식", en:"", cat:"스킨부스터", d:"비가교 히알루론산과 아미노산으로 피부 보습과 잔주름을 가꾸는 스킨부스터예요.", c:["wrinkle_eye"], dt:"some", multi:true, area:"eye", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 잘루프로클래식.html" },
  { n:"필로르가 NCTF135", en:"", cat:"스킨부스터", d:"히알루론산에 여러 영양 성분을 더한 복합 성분으로 피부에 활력을 주는 스킨부스터예요.", c:["dull_tone"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 필로르가 NCTF135.html" },
  { n:"엘라비에리투오", en:"", cat:"스킨부스터", d:"피부 구조 성분인 ECM을 직접 보충하는 차세대 스킨부스터예요.", c:["skin_quality"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 엘라비에리투오.html" },
  { n:"엘라비에리투오파인", en:"", cat:"스킨부스터", d:"엘라비에리투오를 더 작은 입자로 정교하게 만든 ECM 스킨부스터예요.", c:["skin_quality"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 엘라비에리투오파인.html" },
  { n:"연어주사", en:"", cat:"스킨부스터", d:"연어·송어 DNA에서 얻은 PDRN 성분으로 피부 재생을 돕는 주사예요.", c:["regen"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 연어주사.html" },
  { n:"물광주사", en:"", cat:"스킨부스터", d:"히알루론산을 피부 얕은 층에 미세하게 주입해 수분과 물광을 채우는 주사예요.", c:["hydration"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 물광주사.html" },
  { n:"리즈네", en:"", cat:"스킨부스터", d:"연어·송어 DNA 유래 PN 성분으로 피부 재생을 돕는 스킨부스터예요.", c:["regen"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 리즈네.html" },
  { n:"비타란", en:"", cat:"스킨부스터", d:"PN 성분으로 피부 재생과 탄력을 돕는 주사용 스킨부스터예요.", c:["regen"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 비타란.html" },
  { n:"비타란아이", en:"", cat:"스킨부스터", d:"얇은 눈가에 맞춘 PN 성분으로 눈가 잔주름을 가꾸는 스킨부스터예요.", c:["wrinkle_eye"], dt:"some", multi:true, area:"eye", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 비타란아이.html" },
  { n:"울트라콜100", en:"", cat:"스킨부스터", d:"PDO 성분으로 얼굴 전반의 콜라겐 생성을 돕는 스킨부스터형 콜라겐 부스터예요.", c:["skin_quality"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 울트라콜100.html" },
  { n:"울트라콜200", en:"", cat:"스킨부스터", d:"입자가 큰 PDO로 꺼진 부위에 자연스러운 볼륨을 더하는 콜라겐 부스터예요.", c:["volume_cheek"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 울트라콜200.html" },
  { n:"콜라움120", en:"", cat:"스킨부스터", d:"PLLA 성분으로 콜라겐 생성을 돕는 콜라겐 부스터예요.", c:["nasolabial"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 콜라움120.html" },
  { n:"콜라움240", en:"", cat:"스킨부스터", d:"함량을 높인 PLLA로 콜라겐 생성과 볼륨을 함께 돕는 콜라겐 부스터예요.", c:["volume_cheek"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 콜라움240.html" },
  { n:"레스틸렌", en:"", cat:"스킨부스터", d:"안정화 히알루론산을 피부에 채워 수분과 미세주름을 가꾸는 스킨부스터예요.", c:["hydration"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 레스틸렌.html" },
  { n:"레스틸렌비탈라이트", en:"", cat:"스킨부스터", d:"함량을 낮춘 히알루론산으로 얕은 층의 수분과 광채를 가꾸는 스킨부스터예요.", c:["hydration"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 레스틸렌비탈라이트.html" },
  { n:"엘란쎄", en:"", cat:"스킨부스터", d:"PCL 성분으로 즉각 볼륨과 장기 콜라겐 생성을 함께 돕는 콜라겐 부스터예요.", c:["volume_cheek"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 엘란쎄.html" },
  { n:"레디어스", en:"", cat:"스킨부스터", d:"CaHA(칼슘) 성분으로 즉각 볼륨과 콜라겐 생성을 함께 돕는 콜라겐 부스터예요.", c:["volume_cheek"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 레디어스.html" },
  { n:"디클래시 CaHA", en:"", cat:"스킨부스터", d:"CaHA(칼슘) 성분으로 콜라겐 생성과 볼륨을 돕는 콜라겐 부스터예요.", c:["volume_cheek"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 디클래시 CaHA.html" },
  { n:"레티젠", en:"", cat:"스킨부스터", d:"순도 높은 Type 1 콜라겐을 피부에 직접 채워주는 콜라겐 부스터예요.", c:["skin_quality"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 레티젠.html" },
  { n:"리들부스터BH", en:"", cat:"스킨부스터", d:"바르는 스피큘 화장품으로 수분·물광 케어를 돕는 부스터예요.", c:["hydration"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 리들부스터BH.html" },
  { n:"리들부스터PN", en:"", cat:"스킨부스터", d:"바르는 스피큘 화장품에 PN 성분을 더해 재생 케어를 돕는 부스터예요.", c:["aftercare"], dt:"none", multi:true, area:"face", method:"topical", pain:0, onset:"gradual", href:"details/시술소개 - 리들부스터PN.html" },
  { n:"엑소좀", en:"", cat:"스킨부스터", d:"줄기세포 배양액에서 추출한 엑소좀으로 피부 재생 환경을 가꾸는 도포형 케어예요.", c:["aftercare"], dt:"none", multi:true, area:"face", method:"topical", pain:0, onset:"gradual", href:"details/시술소개 - 엑소좀.html" },
  { n:"ASCE+", en:"", cat:"스킨부스터", d:"엑소코바이오의 동결건조 엑소좀을 담은 피부용 도포 부스터예요.", c:["aftercare"], dt:"none", multi:true, area:"face", method:"topical", pain:0, onset:"gradual", href:"details/시술소개 - ASCE.html" },
  { n:"ASCE+HRLV", en:"", cat:"스킨부스터", d:"엑소코바이오의 동결건조 엑소좀을 담은 두피·모발용 도포 부스터예요.", c:["scalp"], dt:"none", multi:true, area:"scalp", method:"topical", pain:0, onset:"gradual", href:"details/시술소개 - ASCE HRLV.html" },
  { n:"볼라썸스킨", en:"", cat:"스킨부스터", d:"CaHA(칼슘) 성분을 얼굴 전반에 얕게 써서 콜라겐 생성을 돕는 콜라겐 부스터예요.", c:["skin_quality"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 볼라썸스킨.html" },
  { n:"볼라썸볼륨", en:"", cat:"스킨부스터", d:"CaHA(칼슘) 성분으로 꺼진 부위에 볼륨과 탄력을 더하는 콜라겐 부스터예요.", c:["volume_cheek"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 볼라썸볼륨.html" },
  { n:"올리디아스킨", en:"", cat:"스킨부스터", d:"PLLA 성분을 얼굴 전반에 얕게 써서 자가 콜라겐 생성을 돕는 스킨부스터예요.", c:["skin_quality"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 올리디아스킨.html" },
  { n:"올리디아볼륨", en:"", cat:"스킨부스터", d:"고함량 PLLA로 꺼진 부위에 자연스러운 볼륨을 채우는 콜라겐 부스터예요.", c:["volume_cheek"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 올리디아볼륨.html" },
  { n:"리제반", en:"", cat:"스킨부스터", d:"연어 유래 PN 성분으로 피부 재생과 탄력을 돕는 스킨부스터예요.", c:["regen"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 리제반.html" },
  { n:"필로드", en:"", cat:"스킨부스터", d:"바다 송어 유래 PN 성분으로 피부 재생과 탄력을 돕는 스킨부스터예요.", c:["regen"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 필로드.html" },
  { n:"벨로테로리바이브", en:"", cat:"스킨부스터", d:"히알루론산과 글리세롤을 함께 담아 수분과 피부결을 채우는 스킨부스터예요.", c:["hydration"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 벨로테로리바이브.html" },
  { n:"쥬브아셀", en:"", cat:"스킨부스터", d:"피부 구조 성분인 ECM을 직접 보충하는 차세대 스킨부스터예요.", c:["skin_quality"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 쥬브아셀.html" },
  { n:"쥬브아셀8%", en:"", cat:"스킨부스터", d:"ECM 함량을 높인 쥬브아셀로 더 적극적인 구조 보강에 초점을 둔 버전이에요.", c:["skin_quality"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 쥬브아셀8.html" },
  { n:"쥬브아셀3%", en:"", cat:"스킨부스터", d:"ECM 함량을 낮춰 비교적 가볍게 적용하는 쥬브아셀 버전이에요.", c:["skin_quality"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 쥬브아셀3.html" },
  { n:"싸이토케어", en:"", cat:"스킨부스터", d:"히알루론산에 여러 영양 성분을 더해 피부에 활력을 주는 스킨부스터예요.", c:["dull_tone"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 싸이토케어.html" },
  { n:"아기주사", en:"", cat:"스킨부스터", d:"피부 성장인자를 보충해 맑고 탄탄한 피부결을 가꾸는 스킨부스터예요.", c:["regen"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 아기주사.html" },
  { n:"베네브아기주사", en:"", cat:"스킨부스터", d:"베네브의 성장인자 복합 앰플로 피부 재생을 돕는 '아기주사' 부스터예요.", c:["regen"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 베네브아기주사.html" },
  { n:"플라좀", en:"", cat:"스킨부스터", d:"PLLA에 PDRN·히알루론산·식물엑소좀을 더한 복합 콜라겐 부스터예요.", c:["skin_quality"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 플라좀.html" },
  { n:"릴리이드", en:"", cat:"스킨부스터", d:"연어 유래 PN 성분으로 피부 재생과 속건조를 가꾸는 스킨부스터예요.", c:["regen"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 릴리이드.html" },
  { n:"릴리이드M", en:"", cat:"스킨부스터", d:"순수 히알루론산으로 속부터 수분을 채우는 물광 스킨부스터예요.", c:["hydration"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 릴리이드M.html" },
  { n:"바이리즌", en:"", cat:"스킨부스터", d:"히알루론산을 담은 바르는 부스터로 수분·피부결 케어를 돕는 화장품이에요.", c:["aftercare"], dt:"none", multi:true, area:"face", method:"topical", pain:0, onset:"gradual", href:"details/시술소개 - 바이리즌.html" },
  { n:"콜라레쥬", en:"", cat:"스킨부스터", d:"콜라겐을 피부에 직접 보충해 탄력과 결을 가꾸는 콜라겐 부스터예요.", c:["skin_quality"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 콜라레쥬.html" },
  { n:"콜라쥬", en:"", cat:"스킨부스터", d:"고순도 콜라겐을 직접 주입해 피부 구조를 보강하는 콜라겐 부스터예요.", c:["skin_quality"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 콜라쥬.html" },
  { n:"에버클", en:"", cat:"스킨부스터", d:"PLLA 성분으로 자가 콜라겐 생성을 유도해 피부결과 수분을 가꾸는 콜라겐 부스터예요.", c:["skin_quality"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 에버클.html" },
  { n:"에버클V", en:"", cat:"스킨부스터", d:"PLLA 함량을 높여 볼륨과 리프팅에 무게를 둔 콜라겐 부스터예요.", c:["volume_cheek"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 에버클V.html" },
  { n:"리쥬비엘W", en:"", cat:"스킨부스터", d:"히알루론산으로 볼륨과 주름을 채우는 필러 라인의 한 제품이에요.", c:["volume_cheek"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 리쥬비엘W.html" },
  { n:"힐로웨이브", en:"", cat:"스킨부스터", d:"고농도 2중 히알루론산으로 깊은 수분과 피부결을 채우는 물광 스킨부스터예요.", c:["hydration"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 힐로웨이브.html" },
  { n:"셀르디엠", en:"", cat:"스킨부스터", d:"피부 구조 성분인 ECM을 직접 보충하는 차세대 스킨부스터예요.", c:["skin_quality"], dt:"some", multi:true, area:"face", method:"injection", pain:2, onset:"gradual", href:"details/시술소개 - 셀르디엠.html" },
  { n:"엑소힐러", en:"", cat:"스킨부스터", d:"제대혈 줄기세포 배양액 엑소좀을 담은 도포형 부스터 화장품이에요.", c:["aftercare"], dt:"none", multi:true, area:"face", method:"topical", pain:0, onset:"gradual", href:"details/시술소개 - 엑소힐러.html" },
  { n:"셀엑소좀", en:"", cat:"스킨부스터", d:"줄기세포 배양액과 식물 유래 엑소좀을 담은 도포형 부스터 화장품이에요.", c:["aftercare"], dt:"none", multi:true, area:"face", method:"topical", pain:0, onset:"gradual", href:"details/시술소개 - 셀엑소좀.html" },
  { n:"셀엑소좀블랙라벨", en:"", cat:"스킨부스터", d:"배양액 성분을 높인 셀엑소좀의 상위 도포형 부스터 화장품이에요.", c:["aftercare"], dt:"none", multi:true, area:"face", method:"topical", pain:0, onset:"gradual", href:"details/시술소개 - 셀엑소좀블랙라벨.html" },
  { n:"세렉소", en:"", cat:"스킨부스터", d:"식물 유래 엑소좀을 담은 도포형 부스터 화장품이에요.", c:["aftercare"], dt:"none", multi:true, area:"face", method:"topical", pain:0, onset:"gradual", href:"details/시술소개 - 세렉소.html" },
  /* ── 레이저·피부 ── */
  { n:"레이저 토닝", en:"", cat:"레이저·피부", d:"저출력 레이저로 색소를 조금씩 분해해 피부톤을 고르게 하는 시술이에요.", c:["pigment"], dt:"none", multi:true, area:"face", method:"laser", pain:1, onset:"gradual", href:"details/시술소개 - 레이저 토닝.html" },
  { n:"피코 레이저", en:"", cat:"레이저·피부", d:"피코초 단위로 색소를 잘게 부숴, 기미·문신·흉터까지 다루는 레이저예요.", c:["pigment"], dt:"some", multi:true, area:"face", method:"laser", pain:1, onset:"gradual", href:"details/시술소개 - 피코 레이저.html" },
  { n:"색소·잡티·문신 제거 레이저", en:"", cat:"레이저·피부", d:"또렷한 잡티·검버섯·문신 색소를 표적해 부숴 빼는 레이저예요.", c:["pigment"], dt:"some", multi:true, area:"face", method:"laser", pain:1, onset:"gradual", href:"details/시술소개 - 색소 잡티 문신 제거 레이저.html" },
  { n:"점·병변 제거 레이저", en:"CO2·어븀야그", cat:"레이저·피부", d:"점·사마귀·검버섯 같은 병변을 얕게 깎아 없애는 레이저예요.", c:["mole"], dt:"some", multi:false, area:"face", method:"laser", pain:1, onset:"gradual", href:"details/시술소개 - 점 병변 제거 레이저.html" },
  { n:"프락셔널 레이저", en:"", cat:"레이저·피부", d:"피부에 미세한 구멍을 촘촘히 내 재생을 유도하는 흉터·모공 레이저예요.", c:["acne_scar"], dt:"some", multi:true, area:"face", method:"laser", pain:1, onset:"gradual", href:"details/시술소개 - 프락셔널 레이저.html" },
  { n:"혈관·홍조 레이저", en:"", cat:"레이저·피부", d:"붉은기·홍조·실핏줄을 일으키는 혈관을 표적해 가라앉히는 레이저예요.", c:["redness"], dt:"some", multi:true, area:"face", method:"laser", pain:1, onset:"gradual", href:"details/시술소개 - 혈관 홍조 레이저.html" },
  { n:"레이저 제네시스", en:"", cat:"레이저·피부", d:"피부 속을 데워 콜라겐을 늘려 모공·홍조·피부결을 다듬는 시술이에요.", c:["pores"], dt:"none", multi:true, area:"face", method:"laser", pain:1, onset:"gradual", href:"details/시술소개 - 레이저 제네시스.html" },
  { n:"IPL·BBL 광선치료", en:"", cat:"레이저·피부", d:"여러 파장의 빛으로 잡티·붉은기를 한 번에 옅게 하는 광선치료예요.", c:["pigment"], dt:"none", multi:true, area:"face", method:"laser", pain:1, onset:"gradual", href:"details/시술소개 - IPL BBL 광선치료.html" },
  { n:"RF 마이크로니들", en:"", cat:"레이저·피부", d:"미세한 바늘로 진피에 고주파 열을 줘 흉터·모공·탄력을 다듬는 시술이에요.", c:["acne_scar"], dt:"some", multi:true, area:"face", method:"needle", pain:3, onset:"gradual", href:"details/시술소개 - RF 마이크로니들.html" },
  { n:"여드름 광치료", en:"PDT·LED", cat:"레이저·피부", d:"빛으로 여드름균과 피지선을 다스려 염증 여드름을 가라앉히는 치료예요.", c:["acne"], dt:"none", multi:true, area:"face", method:"laser", pain:1, onset:"gradual", href:"details/시술소개 - 여드름 광치료.html" },
  { n:"PTT 광열치료", en:"", cat:"레이저·피부", d:"빛에 반응하는 미세 입자로 피지선을 데워 없애는 여드름 치료예요.", c:["acne"], dt:"none", multi:true, area:"face", method:"laser", pain:1, onset:"gradual", href:"details/시술소개 - PTT 광열치료.html" },
  { n:"플라즈마", en:"", cat:"레이저·피부", d:"이온화된 기체 에너지로 표면을 정리하고 진피 재생을 돕는 시술이에요.", c:["acne"], dt:"some", multi:true, area:"face", method:"laser", pain:1, onset:"gradual", href:"details/시술소개 - 플라즈마.html" },
  { n:"LDM 초음파", en:"", cat:"레이저·피부", d:"미세 초음파 진동으로 피부를 진정시키고 재생을 돕는 순한 관리예요.", c:["sensitive"], dt:"none", multi:true, area:"face", method:"laser", pain:1, onset:"gradual", href:"details/시술소개 - LDM 초음파.html" },
  { n:"아쿠아필·하이드라페이셜", en:"", cat:"레이저·피부", d:"물과 흡입으로 모공 속 피지·블랙헤드를 빼내고 수분을 채우는 관리예요.", c:["keratin"], dt:"some", multi:true, area:"face", method:"care", pain:0, onset:"gradual", href:"details/시술소개 - 아쿠아필 하이드라페이셜.html" },
  { n:"서브시전", en:"", cat:"레이저·피부", d:"흉터를 당기는 피부 속 유착을 끊어 새살이 차오르게 돕는 시술이에요.", c:["acne_scar"], dt:"some", multi:false, area:"face", method:"needle", pain:3, onset:"gradual", href:"details/시술소개 - 서브시전.html" },
  { n:"필링", en:"", cat:"레이저·피부", d:"산 성분으로 묵은 각질을 녹여 피부결과 톤을 정돈하는 시술이에요.", c:["keratin"], dt:"none", multi:true, area:"face", method:"care", pain:0, onset:"gradual", href:"details/시술소개 - 필링.html" },
  { n:"손발톱무좀 레이저", en:"", cat:"레이저·피부", d:"레이저 열로 손발톱 속 곰팡이균을 사멸시키는 무좀 치료예요.", c:["nail"], dt:"some", multi:true, area:"nail", method:"laser", pain:1, onset:"gradual", href:"details/시술소개 - 손발톱무좀 레이저.html" },
  /* ── 필러 ── */
  { n:"[필러] 관자놀이", en:"", cat:"필러", d:"꺼진 관자놀이를 채워 야위고 나이 들어 보이는 인상을 부드럽게 보완해요.", c:["volume_temple"], dt:"some", multi:false, area:"face", method:"injection", pain:2, onset:"immediate", href:"details/시술소개 - 필러 관자놀이.html" },
  { n:"[필러] 눈두덩이", en:"", cat:"필러", d:"꺼진 윗꺼풀을 채워 퀭하고 나이 들어 보이는 눈매를 부드럽게 보완해요.", c:["volume_temple"], dt:"some", multi:false, area:"face", method:"injection", pain:2, onset:"immediate", href:"details/시술소개 - 필러 눈두덩이.html" },
  { n:"[필러] 두상", en:"", cat:"필러", d:"납작한 뒤통수나 정수리를 채워 옆·뒤 두상 라인을 둥글게 보완해요.", c:["head_shape"], dt:"some", multi:false, area:"face", method:"injection", pain:2, onset:"immediate", href:"details/시술소개 - 필러 두상.html" },
  { n:"[필러] 제거", en:"", cat:"필러", d:"기존 필러를 분해 효소로 녹여 양을 줄이거나 모양을 되돌리는 시술이에요.", c:["filler_fix"], dt:"some", multi:false, area:"face", method:"injection", pain:2, onset:"immediate", href:"details/시술소개 - 필러 제거.html" },
  { n:"[필러] 인중", en:"", cat:"필러", d:"윗입술에 볼륨을 더해 길어 보이는 인중을 짧고 또렷해 보이게 보완해요.", c:["lips"], dt:"some", multi:false, area:"face", method:"injection", pain:2, onset:"immediate", href:"details/시술소개 - 필러 인중.html" },
  { n:"[필러] 턱라인", en:"", cat:"필러", d:"흐려진 턱선을 따라 볼륨을 보완해 또렷한 윤곽 라인을 만들어요.", c:["contour_chin"], dt:"some", multi:false, area:"face", method:"injection", pain:2, onset:"immediate", href:"details/시술소개 - 필러 턱라인.html" },
  { n:"[필러] 손등", en:"", cat:"필러", d:"꺼지고 마른 손등을 채워 힘줄·혈관이 도드라진 손을 매끈하게 보완해요.", c:["hands"], dt:"some", multi:false, area:"hands", method:"injection", pain:2, onset:"immediate", href:"details/시술소개 - 필러 손등.html" },
  { n:"[필러] 흉터", en:"", cat:"필러", d:"패인 흉터 아래를 채워 피부 표면을 매끈하게 보완해요.", c:["acne_scar"], dt:"some", multi:false, area:"face", method:"injection", pain:2, onset:"immediate", href:"details/시술소개 - 필러 흉터.html" },
  { n:"[필러] 입꼬리", en:"", cat:"필러", d:"처진 입꼬리 아래를 받쳐 올려 부드럽고 환한 인상을 만들어요.", c:["mouth_corner"], dt:"some", multi:false, area:"face", method:"injection", pain:2, onset:"immediate", href:"details/시술소개 - 필러 입꼬리.html" },
  { n:"[필러] 마리오네트", en:"", cat:"필러", d:"입꼬리에서 턱으로 내려가는 처짐 라인을 채워 인상을 부드럽게 풀어줘요.", c:["nasolabial"], dt:"some", multi:false, area:"face", method:"injection", pain:2, onset:"immediate", href:"details/시술소개 - 필러 마리오네트.html" },
  { n:"[필러] 애교살", en:"", cat:"필러", d:"눈 밑 속눈썹 아래에 볼륨을 더해 또렷한 애교살을 만들어요.", c:["eye_charm"], dt:"some", multi:false, area:"eye", method:"injection", pain:2, onset:"immediate", href:"details/시술소개 - 필러 애교살.html" },
  { n:"[필러] 광대", en:"", cat:"필러", d:"꺼진 앞광대에 볼륨을 더해 얼굴에 입체감과 생기를 살려줘요.", c:["volume_cheek"], dt:"some", multi:false, area:"face", method:"injection", pain:2, onset:"immediate", href:"details/시술소개 - 필러 광대.html" },
  { n:"[필러] 볼", en:"", cat:"필러", d:"꺼지고 홀쭉해진 볼을 채워 동안의 통통함과 생기를 살려줘요.", c:["volume_cheek"], dt:"some", multi:false, area:"face", method:"injection", pain:2, onset:"immediate", href:"details/시술소개 - 필러 볼.html" },
  { n:"[필러] 팔자", en:"", cat:"필러", d:"코 옆에서 입가로 패인 팔자 골을 채워 또렷한 인상을 부드럽게 풀어줘요.", c:["nasolabial"], dt:"some", multi:false, area:"face", method:"injection", pain:2, onset:"immediate", href:"details/시술소개 - 필러 팔자.html" },
  { n:"[필러] 입술", en:"", cat:"필러", d:"얇은 입술에 볼륨과 라인을 더해 도톰하고 또렷하게 만들어요.", c:["lips"], dt:"some", multi:false, area:"face", method:"injection", pain:2, onset:"immediate", href:"details/시술소개 - 필러 입술.html" },
  { n:"[필러] 코", en:"", cat:"필러", d:"낮은 콧대나 라인을 채워 수술 없이 코 인상을 보정해요.", c:["nose"], dt:"some", multi:false, area:"face", method:"injection", pain:2, onset:"immediate", href:"details/시술소개 - 필러 코.html" },
  { n:"[필러] 눈밑", en:"", cat:"필러", d:"눈 밑 꺼진 골을 채워 그늘진 다크서클과 피곤한 인상을 완화해요.", c:["volume_eye"], dt:"some", multi:false, area:"eye", method:"injection", pain:2, onset:"immediate", href:"details/시술소개 - 필러 눈밑.html" },
  { n:"[필러] 턱끝", en:"", cat:"필러", d:"짧거나 들어간 턱끝을 채워 옆얼굴 비율을 또렷하게 보완해요.", c:["contour_chin"], dt:"some", multi:false, area:"face", method:"injection", pain:2, onset:"immediate", href:"details/시술소개 - 필러 턱끝.html" },
  /* ── 보톡스 ── */
  { n:"[보톡스] 이갈이/턱관절", en:"", cat:"보톡스", d:"이갈이·이악물기로 과하게 쓰는 턱 근육의 힘을 줄여 통증과 손상을 완화해요.", c:["tmj"], dt:"none", multi:false, area:"face", method:"botox", pain:1, onset:"gradual", href:"details/시술소개 - 보톡스 이갈이 턱관절.html" },
  { n:"[보톡스] 편두통", en:"", cat:"보톡스", d:"만성 편두통의 빈도를 줄이기 위해 머리·목 근육에 주사하는 치료예요.", c:["tmj"], dt:"none", multi:false, area:"face", method:"botox", pain:1, onset:"gradual", href:"details/시술소개 - 보톡스 편두통.html" },
  { n:"[보톡스] 콧볼", en:"", cat:"보톡스", d:"웃을 때 옆으로 벌어지는 콧볼 근육의 움직임을 줄여 완화해요.", c:["mini_botox"], dt:"none", multi:false, area:"face", method:"botox", pain:1, onset:"gradual", href:"details/시술소개 - 보톡스 콧볼.html" },
  { n:"[보톡스] 팔자", en:"", cat:"보톡스", d:"입가 근육의 당김을 줄여 팔자 주변 인상을 보조적으로 완화하는 접근이에요.", c:["nasolabial"], dt:"none", multi:false, area:"face", method:"botox", pain:1, onset:"gradual", href:"details/시술소개 - 보톡스 팔자.html" },
  { n:"[보톡스] 자갈턱", en:"", cat:"보톡스", d:"턱 끝에 자갈처럼 우는 주름을 만드는 근육을 풀어 매끈하게 정돈해요.", c:["mini_botox"], dt:"none", multi:false, area:"face", method:"botox", pain:1, onset:"gradual", href:"details/시술소개 - 보톡스 자갈턱.html" },
  { n:"[보톡스] 콧등", en:"", cat:"보톡스", d:"웃을 때 콧등에 잡히는 가로주름(버니라인)을 만드는 근육을 풀어줘요.", c:["mini_botox"], dt:"none", multi:false, area:"face", method:"botox", pain:1, onset:"gradual", href:"details/시술소개 - 보톡스 콧등.html" },
  { n:"[보톡스] 광경근", en:"", cat:"보톡스", d:"턱을 아래로 당기는 목 근육을 풀어 턱선을 끌어올리고 목 라인을 정돈해요.", c:["neck"], dt:"none", multi:false, area:"neck", method:"botox", pain:1, onset:"gradual", href:"details/시술소개 - 보톡스 광경근.html" },
  { n:"[보톡스] 목주름", en:"", cat:"보톡스", d:"목에 가로로 잡히는 주름 부위의 근육 움직임을 줄여 완화해요.", c:["neck"], dt:"none", multi:false, area:"neck", method:"botox", pain:1, onset:"gradual", href:"details/시술소개 - 보톡스 목주름.html" },
  { n:"[보톡스] 스킨/모공", en:"", cat:"보톡스", d:"피부 표면에 얕게 주입해 모공·피지를 줄이고 피부결을 정돈해요.", c:["pores"], dt:"none", multi:false, area:"face", method:"botox", pain:1, onset:"gradual", href:"details/시술소개 - 보톡스 스킨 모공.html" },
  { n:"[보톡스] 승모근", en:"", cat:"보톡스", d:"발달한 어깨 승모근을 이완시켜 목·어깨 라인을 매끄럽게 정돈해요.", c:["body_line"], dt:"none", multi:false, area:"body", method:"botox", pain:1, onset:"gradual", href:"details/시술소개 - 보톡스 승모근.html" },
  { n:"[보톡스] 종아리", en:"", cat:"보톡스", d:"발달한 종아리 근육을 이완시켜 다리 라인을 매끈하게 정돈해요.", c:["body_line"], dt:"none", multi:false, area:"body", method:"botox", pain:1, onset:"gradual", href:"details/시술소개 - 보톡스 종아리.html" },
  { n:"[보톡스] 다한증", en:"", cat:"보톡스", d:"땀이 과한 부위의 땀샘 신호를 줄여 땀 분비를 완화해요.", c:["sweat"], dt:"none", multi:false, area:"face", method:"botox", pain:1, onset:"gradual", href:"details/시술소개 - 보톡스 다한증.html" },
  { n:"[보톡스] 귀밑샘", en:"", cat:"보톡스", d:"커진 침샘을 줄여 볼·턱밑이 도드라진 얼굴 윤곽을 갸름하게 정돈해요.", c:["face_slim"], dt:"none", multi:false, area:"face", method:"botox", pain:1, onset:"gradual", href:"details/시술소개 - 보톡스 귀밑샘.html" },
  { n:"[보톡스] 잇몸", en:"", cat:"보톡스", d:"웃을 때 윗입술을 과하게 올리는 근육을 풀어 잇몸 노출을 줄여줘요.", c:["gummy"], dt:"none", multi:false, area:"face", method:"botox", pain:1, onset:"gradual", href:"details/시술소개 - 보톡스 잇몸.html" },
  { n:"[보톡스] 사각턱", en:"", cat:"보톡스", d:"발달한 턱 근육을 이완시켜 각진 턱선을 갸름하게 정돈해요.", c:["square_jaw"], dt:"none", multi:false, area:"face", method:"botox", pain:1, onset:"gradual", href:"details/시술소개 - 보톡스 사각턱.html" },
  { n:"[보톡스] 미간", en:"", cat:"보톡스", d:"찡그릴 때 생기는 미간 11자 주름을 만드는 근육을 풀어줘요.", c:["wrinkle_glabella"], dt:"none", multi:false, area:"face", method:"botox", pain:1, onset:"gradual", href:"details/시술소개 - 보톡스 미간.html" },
  { n:"[보톡스] 이마", en:"", cat:"보톡스", d:"눈썹을 올릴 때 생기는 이마 가로주름을 만드는 근육을 풀어줘요.", c:["wrinkle_forehead"], dt:"none", multi:false, area:"face", method:"botox", pain:1, onset:"gradual", href:"details/시술소개 - 보톡스 이마.html" },
  { n:"[보톡스] 눈가", en:"", cat:"보톡스", d:"웃을 때 눈가에 잡히는 잔주름을 만드는 근육을 풀어줘요.", c:["wrinkle_eye"], dt:"none", multi:false, area:"eye", method:"botox", pain:1, onset:"gradual", href:"details/시술소개 - 보톡스 눈가.html" },
];

/* 퀴즈 1단계: 고민 범주 → 세부 고민(id) 묶음 */
const CONCERN_GROUPS = [
  { label:"탄력·리프팅·처짐", concerns:["sagging","elasticity","double_chin"] },
  { label:"주름", concerns:["wrinkle_forehead","wrinkle_glabella","wrinkle_eye","nasolabial","neck","fine_lines"] },
  { label:"피부 재생·결·수분", concerns:["regen","skin_quality","hydration","sensitive","aftercare"] },
  { label:"모공·여드름·흉터", concerns:["pores","acne","acne_scar","keratin"] },
  { label:"색소·홍조·톤", concerns:["pigment","redness","dull_tone","mole"] },
  { label:"볼륨·꺼짐·윤곽보정", concerns:["volume_cheek","volume_eye","volume_temple","contour_chin","nose","lips","eye_charm","mouth_corner"] },
  { label:"얼굴형·표정·근육", concerns:["square_jaw","face_slim","gummy","mini_botox"] },
  { label:"바디·기능", concerns:["body_line","body_skin","sweat","tmj","hands","nail","head_shape","scalp","filler_fix"] },
];

const PAIRS = [
  { a:"울쎄라", b:"써마지", pa:"깊은 SMAS층을 끌어올리는 리프팅", pb:"진피를 데워 조이는 타이트닝", tip:"처진 윤곽이 고민이면 울쎄라, 늘어진 탄력이 고민이면 써마지를 많이 봐요. 둘 다 받기도 하니 내 고민이 '처짐'인지 '탄력'인지부터 정해보세요." },
  { a:"울쎄라", b:"슈링크", pa:"초음파 영상으로 층 보며 시술", pb:"국내 장비로 비용 부담 낮은 편", tip:"같은 HIFU 원리예요. 가격은 샷 수·부위로 갈리니 같은 샷 수·부위 조건인지부터 확인하세요." },
  { a:"울쎄라", b:"인모드", pa:"깊은 층 리프팅에 집중", pb:"국소 지방 감소와 처짐을 함께", tip:"이중턱 같은 지방이 함께 고민이면 인모드, 처짐 중심이면 울쎄라 쪽을 봐요." },
  { a:"써마지", b:"인모드", pa:"진피 전체를 데우는 타이트닝", pb:"지방·탄력을 함께 잡는 복합", tip:"피부결·탄탄함이 목적이면 써마지, 윤곽 살·처짐이 고민이면 인모드를 비교해요." },
  { a:"써마지", b:"올리지오", pa:"수입 모노폴라 고주파", pb:"국내 모노폴라 고주파", tip:"방식이 비슷해요. 샷 수와 정품 팁 여부를 같은 조건으로 두고 비교하세요." },
  { a:"써마지", b:"덴서티", pa:"단극성 고주파 타이트닝", pb:"단극성+양극성 함께 사용", tip:"덴서티는 깊고 얕은 층을 함께 다뤄요. 같은 샷 수·부위 기준으로 보는 게 좋아요." },
  { a:"올리지오", b:"덴서티", pa:"모노폴라 고주파", pb:"모노폴라+바이폴라 복합", tip:"둘 다 국내 RF예요. 한 가지 깊이냐, 여러 깊이냐의 차이를 보고 고르세요." },
  { a:"올리지오", b:"볼뉴머", pa:"모노폴라 RF 타이트닝", pb:"모노폴라 RF, 부위별 시술", tip:"방식이 비슷한 국내 RF예요. 샷 수·부위·정품 팁 조건을 맞춰 비교하세요." },
  { a:"슈링크", b:"더블로골드", pa:"점·선 조사 HIFU", pb:"합리적 비용의 HIFU", tip:"둘 다 국내 HIFU 리프팅이에요. 샷 수와 부위가 같은 조건인지 확인하세요." },
  { a:"슈링크", b:"리프테라", pa:"또렷한 변화 중심 HIFU", pb:"부담 적은 입문형 HIFU", tip:"강하게 한 번이냐, 가볍게 자주냐의 차이예요. 통증·다운타임 선호로 골라보세요." },
  { a:"인모드", b:"온다", pa:"고주파+진공 흡입", pb:"극초단파(마이크로웨이브)", tip:"둘 다 지방·탄력을 함께 봐요. 부위와 횟수 조건을 맞춰 비교하세요." },
  { a:"텐써마", b:"텐쎄라", pa:"고출력 고주파 타이트닝", pb:"2라인 초음파 리프팅", tip:"이름은 비슷하지만 텐써마는 RF, 텐쎄라는 HIFU예요. 탄력이냐 처짐이냐로 갈라봐요." },
  { a:"소프웨이브", b:"울쎄라", pa:"진피 1.5mm, 표면 손상 적음", pb:"깊은 SMAS층까지 리프팅", tip:"잔주름·민감 부위는 소프웨이브, 깊은 처짐은 울쎄라를 많이 봐요." },
  { a:"쿨소닉", b:"울쎄라", pa:"냉각으로 통증 줄인 HIFU", pb:"초음파 영상으로 층 확인", tip:"통증 부담이 크면 쿨소닉을 고려해요. 샷 수·부위는 같은 조건으로 비교하세요." },
  { a:"프로파운드", b:"울쎄라", pa:"니들로 진피·피하 직접 가열", pb:"초음파로 SMAS층 가열", tip:"둘 다 강한 리프팅이에요. 니들 방식이냐 초음파냐, 다운타임 차이를 보고 고르세요." },
  { a:"모피우스8", b:"포텐자", pa:"진피·지방층까지 니들 RF", pb:"깊이별 맞춤 니들 RF", tip:"둘 다 미세침 고주파예요. 흉터·모공 중심인지, 깊은 처짐까지인지로 비교해요." },
  { a:"버츄RF", b:"포텐자", pa:"표피 자극 적은 니들 RF", pb:"깊이별 맞춤 니들 RF", tip:"방식이 비슷한 니들 RF예요. 팁 정품 여부와 부위 조건을 맞춰 비교하세요." },
  { a:"모피우스8", b:"인모드", pa:"니들로 깊은 층 리모델링", pb:"FX·Forma로 지방·탄력", tip:"같은 인모드 계열이에요. 바늘 없이 받을지, 니들로 깊게 갈지로 갈려요." },
  { a:"엠페이스", b:"울쎄라", pa:"고주파+근육 전기 자극", pb:"초음파로 깊은 층 리프팅", tip:"근육층까지 함께 보고 싶으면 엠페이스, 깊은 처짐은 울쎄라를 비교해요." },
  { a:"슈링크", b:"써마지", pa:"초음파 HIFU 리프팅", pb:"고주파 RF 타이트닝", tip:"원리가 달라요. 처짐엔 HIFU(슈링크), 탄탄함엔 RF(써마지) 쪽을 봐요." },
  { a:"리쥬란힐러", b:"쥬베룩", pa:"PN 성분 재생 스킨부스터", pb:"PDLLA 콜라겐 부스터", tip:"재생·결 중심이면 리쥬란, 콜라겐 생성·탄력이면 쥬베룩을 많이 비교해요." },
  { a:"리쥬란힐러", b:"물광주사", pa:"PN 성분으로 재생·탄력", pb:"히알루론산으로 수분·물광", tip:"재생이 목적이면 리쥬란, 촉촉한 수분감이면 물광주사 쪽이에요." },
  { a:"리쥬란힐러", b:"연어주사", pa:"정제 PN, 엠보싱 관리 필요", pb:"PDRN 성분 재생 주사", tip:"둘 다 연어 유래 재생 성분이에요. 성분 정제도·통증·가격 조건을 보고 비교해요." },
  { a:"리쥬란힐러", b:"스킨바이브", pa:"PN 성분으로 재생", pb:"히알루론산으로 수분·결", tip:"재생이냐 수분이냐가 갈려요. 내 피부가 '얇고 처짐'인지 '건조'인지부터 보세요." },
  { a:"쥬베룩", b:"스컬트라", pa:"PDLLA 콜라겐 부스터", pb:"PLLA 콜라겐 부스터", tip:"둘 다 콜라겐 생성을 유도해요. 성분과 유지 기간, 가격 조건을 맞춰 비교하세요." },
  { a:"스컬트라", b:"엘란쎄", pa:"PLLA, 서서히 콜라겐 생성", pb:"PCL, 즉각 볼륨+장기 콜라겐", tip:"자연스러운 점진 개선은 스컬트라, 바로 볼륨감까지는 엘란쎄를 봐요." },
  { a:"물광주사", b:"스킨바이브", pa:"얕은 층 수분·물광", pb:"히알루론산 수분·결, 지속력", tip:"둘 다 HA 수분 시술이에요. 지속 기간과 가격 조건을 같이 두고 비교하세요." },
  { a:"리쥬란아이", b:"쥬베룩아이", pa:"눈가용 PN 재생 부스터", pb:"눈가용 PDLLA 콜라겐 부스터", tip:"얇은 눈가 전용인 점은 같아요. 재생 중심인지 콜라겐 중심인지로 갈라봐요." },
  { a:"연어주사", b:"물광주사", pa:"PDRN 성분 재생", pb:"히알루론산 수분·물광", tip:"재생이 목적이면 연어주사, 수분이 목적이면 물광주사를 많이 비교해요." },
  { a:"쥬베룩볼륨", b:"스컬트라", pa:"큰 입자 PDLLA로 볼륨", pb:"PLLA로 전반 콜라겐", tip:"꺼진 부위 볼륨이면 쥬베룩볼륨, 얼굴 전반 탄력이면 스컬트라를 봐요." },
  { a:"엘란쎄", b:"레디어스", pa:"PCL 성분 볼륨·콜라겐", pb:"CaHA(칼슘) 볼륨·콜라겐", tip:"둘 다 즉각 볼륨+콜라겐이에요. 성분과 유지 기간을 보고 비교하세요." },
  { a:"레디어스", b:"스컬트라", pa:"CaHA, 즉각 볼륨감", pb:"PLLA, 서서히 자연스럽게", tip:"바로 윤곽이 잡히는 건 레디어스, 티 안 나게 차오르는 건 스컬트라예요." },
  { a:"레이저 토닝", b:"피코 레이저", pa:"저출력으로 색소 조금씩", pb:"피코초로 색소 잘게 분해", tip:"은은한 토닝이냐, 또렷한 색소·문신까지냐의 차이예요. 색소 종류로 갈려요." },
  { a:"프락셔널 레이저", b:"서브시전", pa:"미세 구멍으로 재생 유도", pb:"흉터 유착을 끊어 박리", tip:"흉터에 자주 함께 써요. 표면 재생이냐, 당기는 유착을 끊느냐로 역할이 달라요." },
  { a:"아쿠아필·하이드라페이셜", b:"필링", pa:"물·흡입으로 모공 클렌징", pb:"산 성분으로 각질 정돈", tip:"모공 속 피지·블랙헤드는 아쿠아필, 묵은 각질·톤은 필링을 많이 봐요." },
  { a:"[필러] 팔자", b:"[보톡스] 팔자", pa:"꺼진 골을 채워 완화", pb:"입가 근육 당김을 보조 완화", tip:"팔자는 필러로 채우는 게 기본이고 보톡스는 보조적이에요. 원인에 따라 상담으로 정해요." },
  { a:"[필러] 눈밑", b:"쥬베룩아이", pa:"꺼진 골을 채워 그늘 완화", pb:"얇은 눈가 재생·결 케어", tip:"눈밑 '꺼짐'은 필러, 얇아진 '피부결'은 부스터를 봐요. 다크서클 원인에 따라 갈려요." },
];

const TERMS = [
  { t:"HIFU (고강도 집속 초음파)", d:"초음파 열을 피부 속 한 점에 모아 콜라겐 재생을 유도하는 리프팅 방식이에요." },
  { t:"RF (고주파)", d:"고주파 전류가 만드는 열로 진피 콜라겐을 자극해 탄력을 돕는 방식이에요." },
  { t:"SMAS층", d:"피부 깊은 곳의 근막층으로, 리프팅 시술이 끌어올리려는 목표 층이에요." },
  { t:"PN·PDRN", d:"연어·송어 DNA에서 얻은 성분으로, 피부 재생을 돕는 것으로 알려져 있어요." },
  { t:"스킨부스터", d:"피부 속에 재생·수분 성분을 미세하게 주입해 피부결과 탄력을 가꾸는 시술을 통칭해요." },
  { t:"콜라겐 부스터", d:"PLLA·PDO·CaHA 등으로 피부가 스스로 콜라겐을 만들도록 자극하는 시술이에요." },
  { t:"다운타임", d:"시술 후 붓기·멍 등으로 일상에 약간 불편이 있는 회복 기간을 말해요." },
];

/* ⑤ 시술 꿀TIP — 페이지 새로고침 시 랜덤 노출 */
const TIPS = [
  { cat:"검색·비교", t:"같은 '조건'끼리 비교하세요", d:"샷 수·부위·용량·횟수가 다르면 가격도 달라요. 비교는 이 조건부터 맞춰보세요." },
  { cat:"검색·비교", t:"HIFU·RF는 '샷 수'가 가른다", d:"같은 부위라도 300샷과 600샷은 가격이 크게 달라요." },
  { cat:"검색·비교", t:"정품 팁·카트리지 확인", d:"1회용 정품 팁을 쓰는지에 따라 가격과 안전성이 달라질 수 있어요." },
  { cat:"검색·비교", t:"패키지는 1회당으로 환산", d:"총액을 횟수로 나눠 '1회당 가격'으로 보면 비교가 쉬워요." },
  { cat:"검색·비교", t:"이벤트가에 빠진 항목 확인", d:"마취·재생관리·정품 추가비가 따로면 총액이 달라져요." },
  { cat:"검색·비교", t:"보톡스는 '유닛', 필러는 'cc'", d:"같은 단위·같은 제품 기준으로 봐야 진짜 비교예요." },
  { cat:"검색·비교", t:"필러는 제품이 가격을 가른다", d:"같은 부위라도 국산인지 수입인지에 따라 달라져요." },
  { cat:"검색·비교", t:"후기보다 '조건'을 보세요", d:"후기는 사람마다 달라요. 용량·부위·횟수 같은 조건이 더 정확한 기준이에요." },
  { cat:"검색·비교", t:"'전체'인지 '부분'인지 확인", d:"같은 시술명이라도 범위가 다르면 가격이 크게 달라져요." },
  { cat:"검색·비교", t:"너무 싼 가격은 구성 의심", d:"샷 수가 적거나 정품이 아닐 수 있으니 구성을 꼭 확인하세요." },
  { cat:"검색·비교", t:"모드·옵션도 가격 변수", d:"인모드 FX·Forma·듀얼처럼 어떤 모드인지에 따라 가격이 달라져요." },
  { cat:"검색·비교", t:"같은 성분도 제품이 여럿", d:"PN·PDRN·콜라겐 부스터는 제품마다 특징과 가격이 달라요." },
  { cat:"검색·비교", t:"리프팅과 타이트닝은 목적이 다름", d:"처짐엔 리프팅, 늘어진 탄력엔 타이트닝을 비교해 보세요." },
  { cat:"검색·비교", t:"비교 전 내 고민 한 줄로", d:"'처짐'인지 '탄력'인지 '볼륨'인지 정하면 비교가 빨라져요." },
  { cat:"검색·비교", t:"유지 기간까지 같이 보기", d:"유지가 짧으면 자주 받아야 해 총비용이 달라질 수 있어요." },
  { cat:"검색·비교", t:"추가 관리 포함 여부", d:"시술 후 진정·재생 관리가 포함인지 별도인지 확인하면 좋아요." },
  { cat:"검색·비교", t:"같은 HIFU도 장비가 달라요", d:"슈링크·울쎄라처럼 원리가 같아도 장비마다 특징이 달라요." },
  { cat:"검색·비교", t:"'조건의 투명성'을 보세요", d:"무엇이 포함됐는지 명확히 안내하는 곳이 비교하기 좋아요." },
  { cat:"시술 이해", t:"울쎄라 vs 써마지", d:"울쎄라는 깊은 층을 끌어올리는 리프팅, 써마지는 진피를 데우는 타이트닝이에요." },
  { cat:"시술 이해", t:"슈링크 vs 울쎄라", d:"둘 다 HIFU예요. 울쎄라는 영상으로 층을 보며, 슈링크는 비용 부담이 낮은 편이에요." },
  { cat:"시술 이해", t:"HIFU가 뭐예요?", d:"초음파 열을 피부 속 한 점에 모아 콜라겐 재생을 유도하는 리프팅 방식이에요." },
  { cat:"시술 이해", t:"RF(고주파)가 뭐예요?", d:"고주파로 만든 열로 진피 콜라겐을 자극해 탄력을 돕는 방식이에요." },
  { cat:"시술 이해", t:"SMAS층이 뭐예요?", d:"피부 깊은 곳의 근막층으로, 리프팅이 끌어올리려는 목표 층이에요." },
  { cat:"시술 이해", t:"PN·PDRN 차이", d:"둘 다 연어·송어 DNA 유래 재생 성분으로, 정제 정도·제형에 차이가 있어요." },
  { cat:"시술 이해", t:"스킨부스터란?", d:"피부 속에 재생·수분 성분을 미세하게 넣어 결과 탄력을 가꾸는 시술의 총칭이에요." },
  { cat:"시술 이해", t:"콜라겐 부스터란?", d:"PLLA·PDO·CaHA 등으로 피부가 스스로 콜라겐을 만들게 자극하는 시술이에요." },
  { cat:"시술 이해", t:"필러 vs 부스터", d:"필러는 볼륨을 채우고, 부스터는 피부 자체의 재생·수분에 초점이 있어요." },
  { cat:"시술 이해", t:"보톡스의 원리", d:"근육 움직임을 줄여, 표정으로 생기는 주름을 완화하는 시술이에요." },
  { cat:"시술 이해", t:"보톡스 효과 시점", d:"보통 3~7일부터 나타나 2~4주에 가장 뚜렷해져요(개인차 있음)." },
  { cat:"시술 이해", t:"사각턱 보톡스 시점", d:"근육이 줄며 보통 2~3주부터 갸름해져요. 직후 바로는 아니에요." },
  { cat:"시술 이해", t:"HIFU 효과 시점", d:"직후 당김이 느껴지고, 콜라겐이 재생되며 약 2~3개월에 걸쳐 또렷해져요." },
  { cat:"시술 이해", t:"다운타임이란?", d:"붓기·멍·자국으로 일상이 조금 불편한 회복 기간을 말해요." },
  { cat:"시술 이해", t:"니들 RF란?", d:"미세 바늘로 진피에 직접 고주파를 줘 흉터·모공·탄력을 다듬는 방식이에요." },
  { cat:"시술 이해", t:"토닝 vs 피코", d:"토닝은 색소를 은은하게, 피코는 더 잘게 부숴 또렷한 색소·문신까지 다뤄요." },
  { cat:"시술 이해", t:"인모드 FX·Forma", d:"FX는 국소 지방, Forma는 탄력에 초점이에요. 둘 다면 듀얼을 고려해요." },
  { cat:"시술 이해", t:"표정 주름 vs 고정 주름", d:"보톡스는 표정으로 생기는 주름에 주로 도움을 줘요. 깊게 고정된 주름은 다를 수 있어요." },
  { cat:"시술 이해", t:"즉각 효과 vs 점진 효과", d:"필러는 바로 보이고, 부스터·콜라겐은 서서히 자연스럽게 나타나요." },
  { cat:"시술 이해", t:"색소는 한 번에 안 빠져요", d:"기미·잡티는 보통 여러 번 나눠 관리하는 경우가 많아요." },
  { cat:"시술 이해", t:"흉터는 복합 접근", d:"패인 흉터는 레이저·니들RF·서브시전 등을 함께 쓰기도 해요." },
  { cat:"시술 이해", t:"마취 방식도 시술마다", d:"크림·수면 등 마취는 시술·개인에 따라 달라요. 미리 확인하세요." },
  { cat:"시술 전", t:"상담 때 사진 남기기", d:"정면·측면 사진을 찍어두면 전후 변화를 비교하기 좋아요." },
  { cat:"시술 전", t:"복용 약은 미리 알리기", d:"약·영양제는 멍·출혈에 영향 줄 수 있어 미리 알리고 상의하세요." },
  { cat:"시술 전", t:"임신·수유는 꼭 고지", d:"임신·수유 중이거나 계획이 있으면 시술 전 반드시 알려주세요." },
  { cat:"시술 전", t:"신경근 질환 고지", d:"보톡스는 신경근 질환이 있으면 제한될 수 있어 미리 알려야 해요." },
  { cat:"시술 전", t:"중요한 일정 전 여유 두기", d:"멍·붓기가 생길 수 있으니 행사 1~2주 전엔 여유를 두세요." },
  { cat:"시술 전", t:"음주는 전날부터 자제", d:"음주는 붓기·멍을 키울 수 있어 시술 전후로 피하는 게 좋아요." },
  { cat:"시술 전", t:"기대치는 솔직하게", d:"원하는 정도를 구체적으로 말하면 용량·범위를 맞추기 좋아요." },
  { cat:"시술 전", t:"한 번에 다 하려 하지 않기", d:"여러 시술을 겹칠 땐 순서·간격을 의료진과 상의하세요." },
  { cat:"시술 전", t:"첫 시술은 보수적으로", d:"처음이면 적은 용량으로 시작해 반응을 보는 것도 방법이에요." },
  { cat:"시술 전", t:"알레르기·반응 이력 공유", d:"과거 시술 반응이나 알레르기가 있으면 미리 알려주세요." },
  { cat:"시술 전", t:"각질·레티노이드 상의", d:"강한 각질제거·레티노이드 사용 중이면 중단 시점을 상의하세요." },
  { cat:"시술 전", t:"생리 주기 고려", d:"생리 기간엔 붓기·통증이 더 느껴질 수 있어 참고하세요." },
  { cat:"시술 전", t:"정품·유효기간 확인 가능", d:"사용 제품의 정품 여부를 물어볼 수 있어요. 꺼리지 않아도 돼요." },
  { cat:"시술 전", t:"시술 범위 명확히", d:"'눈가만'인지 '눈가+미간'인지 범위를 분명히 하면 가격·결과가 또렷해요." },
  { cat:"시술 전", t:"컨디션 좋은 날에", d:"피곤한 날은 붓기·회복에 영향 줄 수 있어요." },
  { cat:"시술 전", t:"직후 일정은 가볍게", d:"마취·붓기 가능성이 있으니 시술 직후 일정은 가볍게 잡으세요." },
  { cat:"시술 전", t:"궁금하면 다 물어보기", d:"마취·통증·다운타임·유지 기간은 상담 때 미리 확인하세요." },
  { cat:"시술 전", t:"당일 화장은 가볍게", d:"시술 당일은 진한 메이크업보다 가볍게 하고 가면 편해요." },
  { cat:"시술 후", t:"보톡스 후 4시간", d:"시술 후 약 4시간은 눕지 말고 시술 부위를 문지르지 마세요." },
  { cat:"시술 후", t:"보톡스 당일 금지", d:"당일 음주·사우나·격한 운동은 피하는 게 좋아요." },
  { cat:"시술 후", t:"사각턱 보톡스와 음식", d:"딱딱하고 질긴 음식을 자주 씹으면 효과가 빨리 줄 수 있어요." },
  { cat:"시술 후", t:"필러 후 멍·부기", d:"보통 며칠 내 가라앉아요. 냉찜질이 도움이 될 수 있어요." },
  { cat:"시술 후", t:"필러 부위 압박 주의", d:"세게 누르거나 마사지하지 마세요(의료진 안내 우선)." },
  { cat:"시술 후", t:"입술 필러 후", d:"멍·부기가 흔해요. 자극적이거나 뜨거운 음식은 잠시 피하세요." },
  { cat:"시술 후", t:"눈밑 필러 틴들현상", d:"푸르스름하게 비치면 녹여 조정할 수 있으니 의료진과 상의하세요." },
  { cat:"시술 후", t:"스킨부스터 엠보싱", d:"주입 자국은 보통 2~3일이면 가라앉아요. 건드리지 마세요." },
  { cat:"시술 후", t:"레이저 후 자외선 차단", d:"색소 시술 후엔 자외선 차단이 특히 중요해요. 꾸준히 발라주세요." },
  { cat:"시술 후", t:"딱지는 떼지 말기", d:"점·병변 제거 후 딱지는 자연히 떨어질 때까지 두세요." },
  { cat:"시술 후", t:"보습·진정이 회복 도움", d:"레이저·필링 후엔 보습과 진정 관리가 회복에 도움이 돼요." },
  { cat:"시술 후", t:"사우나·찜질 며칠 자제", d:"열은 붓기·홍조를 키울 수 있어 며칠은 피하는 게 좋아요." },
  { cat:"시술 후", t:"시술 후 음주 자제", d:"음주는 붓기·멍·홍조를 키울 수 있어요." },
  { cat:"시술 후", t:"격한 운동 잠시 쉬기", d:"당일~며칠은 땀·열이 많은 운동을 피하는 게 좋아요." },
  { cat:"시술 후", t:"HIFU·RF 후", d:"다운타임은 거의 없지만 붓기·홍조가 며칠 갈 수 있어요." },
  { cat:"시술 후", t:"효과는 기다려 주세요", d:"콜라겐 재생형 시술은 몇 주~몇 달에 걸쳐 서서히 나타나요." },
  { cat:"시술 후", t:"이마 보톡스 후 느낌", d:"한동안 눈썹이 무겁게 느껴질 수 있어요. 보통 차차 적응돼요." },
  { cat:"시술 후", t:"멍이 생겨도", d:"보통 며칠~1~2주면 옅어져요. 심하면 의료진과 상의하세요." },
  { cat:"시술 후", t:"시술 후 화장 시점", d:"부위·시술에 따라 달라요. 언제부터 가능한지 미리 확인하세요." },
  { cat:"시술 후", t:"자극 성분 잠시 멈춤", d:"시술 후 며칠은 레티노이드·강한 각질제거를 쉬는 게 좋아요." },
  { cat:"시술 후", t:"수분·휴식 챙기기", d:"물을 충분히 마시고 잘 쉬면 회복에 도움이 돼요." },
  { cat:"시술 후", t:"이상 신호는 바로 연락", d:"심한 통증·발열·창백함·시야 변화 등은 즉시 의료기관에 연락하세요." },
  { cat:"시술 후", t:"재시술 간격 지키기", d:"필러·보톡스는 적절한 간격을 두는 게 자연스럽고 안전해요." },
  { cat:"시술 후", t:"시술일·변화 기록", d:"시술일과 효과 변화를 메모하면 다음 시점을 잡기 좋아요." },
  { cat:"시술 후", t:"관리 지시 따르기", d:"일부 시술은 가벼운 마사지를 권하기도 해요. 안내대로 하세요." },
  { cat:"피부 관리", t:"자외선 차단이 기본", d:"자외선은 색소·노화의 큰 원인이에요. 매일 차단제를 챙기면 효과 유지에 도움돼요." },
  { cat:"피부 관리", t:"차단제는 충분히", d:"권장량보다 적게 바르면 효과가 떨어져요. 꼼꼼히 펴 발라주세요." },
  { cat:"피부 관리", t:"흐린 날·실내도 자외선", d:"흐린 날·창가에도 자외선이 있어요. 차단은 꾸준히가 핵심이에요." },
  { cat:"피부 관리", t:"보습으로 장벽 지키기", d:"피부 장벽이 튼튼하면 회복도, 결도 좋아져요." },
  { cat:"피부 관리", t:"과한 각질 제거 주의", d:"너무 자주 벗겨내면 장벽이 약해져 예민해질 수 있어요." },
  { cat:"피부 관리", t:"수면·식습관도 피부", d:"충분한 수면과 균형 잡힌 식사가 피부 컨디션에 도움이 돼요." },
  { cat:"피부 관리", t:"금연이 피부에도", d:"흡연은 콜라겐·혈류에 영향을 줘 노화·회복에 불리해요." },
  { cat:"피부 관리", t:"뜨거운 물 세안 주의", d:"너무 뜨거운 물은 건조·홍조를 키울 수 있어요. 미온수가 좋아요." },
  { cat:"피부 관리", t:"새 제품은 패치 테스트", d:"자극 가능성이 있으니 팔 안쪽 등에 먼저 테스트해 보세요." },
  { cat:"피부 관리", t:"레티노이드는 서서히", d:"처음엔 낮은 농도·간헐 사용으로 적응시키는 게 좋아요." },
  { cat:"피부 관리", t:"홈케어는 거들 뿐", d:"효과 유지엔 도움이 되지만, 시술을 대체하진 못해요." },
  { cat:"피부 관리", t:"색소엔 차단이 먼저", d:"색소 관리 중엔 자외선 차단이 시술만큼 중요해요." },
  { cat:"피부 관리", t:"보습은 시술 효과의 친구", d:"충분한 보습은 결·탄력 시술의 결과를 더 오래 가게 도와요." },
  { cat:"피부 관리", t:"피부 일기 써보기", d:"제품·시술·반응을 기록하면 내게 맞는 걸 찾기 쉬워요." },
  { cat:"피부 관리", t:"계절 따라 루틴 조정", d:"건조한 계절엔 보습을, 자외선 강한 계절엔 차단을 강화하세요." },
  { cat:"피부 관리", t:"무리한 셀프 시술 금지", d:"집에서 하는 강한 기기·니들은 감염·흉터 위험이 있어요." },
  { cat:"안전·정품", t:"의료기관·전문의 확인", d:"시술은 의료 행위예요. 의료기관과 담당 의료진을 확인하세요." },
  { cat:"안전·정품", t:"정품 여부 물어보기", d:"사용 제품·팁의 정품 여부는 물어볼 권리가 있어요." },
  { cat:"안전·정품", t:"식약처 허가 제품인지", d:"국내 허가된 제품인지 확인하면 안전에 도움이 돼요." },
  { cat:"안전·정품", t:"과한 광고 문구 경계", d:"'100% 완성' 같은 단정 표현은 의료광고로 부적절할 수 있어요." },
  { cat:"안전·정품", t:"부작용 설명도 듣기", d:"효과만큼 부작용·주의사항도 충분히 안내받는 게 중요해요." },
  { cat:"안전·정품", t:"응급 연락처 확인", d:"시술 후 문제 생길 때 연락할 곳을 미리 알아두세요." },
  { cat:"안전·정품", t:"너무 잦은 시술 경계", d:"반복이 잦으면 조직이 늘어나거나 부담이 될 수 있어요." },
  { cat:"안전·정품", t:"내 몸 상태 우선", d:"컨디션·질환·약을 솔직히 공유하는 게 안전의 시작이에요." },
  { cat:"안전·정품", t:"동의서 꼼꼼히 읽기", d:"효과·부작용·주의사항이 담긴 동의서를 읽어보세요." },
  { cat:"안전·정품", t:"비교는 정보, 결정은 상담", d:"조건은 앱으로 비교하되, 최종 결정은 의료진 상담으로 하세요." },
  { cat:"안전·정품", t:"효과엔 개인차", d:"같은 시술도 사람마다 결과가 달라요. 보장은 없다는 걸 기억하세요." },
];
